config/routes.rb
Photogur::Application.routes.draw do
 # post 'pictures' => "pictures#create" 

 # get 'pictures' => 'pictures#index'

 # get 'pictures/new' => 'pictures#new', as: "new_picture"
 # get 'pictures/:id' => 'pictures#show', as: "picture"

 # get 'pictures/:id/edit' => 'pictures#edit', as: "edit_picture"

 resources :pictures
 root :to => "pictures#index"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :artist, :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def index
		@pictures = Picture.all.reverse
	end

	def show
		@picture = Picture.find(params[:id])
	end		

	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.new(params[:picture])
		if @picture.save
			redirect_to pictures_url
		else
			render :new
		end
		
	end
	
	def edit
		@picture =Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])

		if @picture.update_attributes(params[:picture])
			redirect_to "/pictures/#{@picture.id}"
		else
			render :edit
			
		end	
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_url
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">
	<%= yield %>
	</div>
</div>
</body>
</html>

app/views/pictures/edit.html.erb
<div class="span12"><h1>Edit: <%= @picture[:title] %> - <%= @picture[:artist] %></h1>  </div>
<p>
  <%= link_to "Back", @picture, :class => "btn btn-inverse"%>
</p>
<div class="row-fluid">
      <div class="span6">
      <%= form_for @picture do |f| %>
        <p>
          <%= f.label "artist" %><br>
          <%= f.text_field "artist" %>
        </p>
        <p>
          <%= f.label "title" %><br>
          <%= f.text_field "title" %>
        </p>
        <p>
          <%= f.label "url" %><br>
          <%= f.text_field "url" %>
        </p>
        <p>
          <%= submit_tag "Save", :class => "btn btn-warning" %>
        </p>
      <% end %>
    </div>
  </div>

app/views/pictures/index.html.erb
 	<div class="span12"><h1 style="margin-bottom:20px">Made in Brazil</h1> 
 	<h6><br>Showcasing the best artists from Brazil <br> <%= @pictures.length %> images</h6>	</div>
 	<%= link_to "Add New Picture", "/pictures/new", :class => "btn btn-inverse" %>


	<div class="row-fluid">
		<% @pictures.each do |picture| %>
	  <div class="span4 image-container">
		<p><%= picture[:title] %> - <%= picture[:artist] %><br><br></p>
  		<%= link_to image_tag(picture.url), "/pictures/#{picture.id}", :class => "image-max" %>
  			<br><br><br><br>
  	</div>
  			<% end %>

	</div>

app/views/pictures/new.html.erb
 	<div class="span12"><h1>Add a picture</h1>
 		 	</div>
 							<%= link_to "Back to Pictures", pictures_url, :class => "btn btn-inverse"  %>


<div class="row-fluid">
      <div class="span6">
				<%= form_for @picture do |f| %>
				<p>
					<%= f.label "artist" %>	<%= f.text_field "artist" %>
				</p>
				<p>
					<%= f.label "title" %>
					<%= f.text_field "title" %>
				</p>
				<p>
					<%= f.label "url" %>
					<%= f.text_field "url" %>
				</p>

					<div class="btn btn-warning">
						<%= f.submit "save" %>
					</div>
				<% end %>
			
			</div>
		</div>

app/views/pictures/picture0.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src = "<% @picture[:url] %>" >

app/views/pictures/picture1.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src = "<% @picture[:url] %>" >

app/views/pictures/picture2.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src = "<% @picture[:url] %>" >

app/views/pictures/show.html.erb
 	<div class="span12"><h1><%= @picture[:title] %> - <%= @picture[:artist] %></h1> 	</div>
 	<div class="btn btn-inverse">
 		<%= link_to "Back to Pictures", pictures_url %></div>
<div class="btn btn-inverse">
 	<%= link_to "Edit", edit_picture_path(@picture) %></div>
<div class="btn btn-inverse">
 	<%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => :delete %>
 	</div>

<p></p>

	<div class="row-fluid">
      <div class="span11">
<%= image_tag @picture.url %>
</div>
</div>